# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, verbose_name='Bio (Markdown)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos/', verbose_name='Foto')),
                ('affiliation', models.CharField(blank=True, max_length=200, verbose_name='Affiliation')),
                ('position', models.CharField(blank=True, help_text='z. B. Head of Lab Medicine, Univ.-Klinik Salzburg', max_length=200, verbose_name='Position')),
                ('country', models.CharField(blank=True, help_text='Land der Affiliation, z. B. Österreich', max_length=120, verbose_name='Land')),
                ('country_iso', models.CharField(blank=True, help_text="z. B. 'AT' für Flag-Anzeige", max_length=2, verbose_name='ISO-3166')),
                ('cv', models.FileField(blank=True, help_text='PDF mit Lebenslauf', null=True, upload_to='people/cv/', verbose_name='CV')),
                ('pronouns', models.CharField(blank=True, help_text='z. B. er/ihm oder she/her — leer = nicht angezeigt', max_length=40, verbose_name='Pronomen')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('orcid', models.CharField(blank=True, help_text='Format: 0000-0000-0000-0000', max_length=19, verbose_name='ORCID')),
                ('website', models.URLField(blank=True, verbose_name='Webseite')),
                ('profile_public', models.BooleanField(default=False, help_text='Erst nach expliziter ConsentRecord auf True setzen', verbose_name='Profil öffentlich')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='lma_core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personenprofil',
                'verbose_name_plural': 'Personenprofile',
                'ordering': ['event', 'user__last_name', 'user__first_name'],
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talk_subjects', models.CharField(blank=True, help_text='Komma-separiert, z. B. Präanalytik, KI, Hämatologie', max_length=400, verbose_name='Themen-Tags')),
                ('short_intro', models.CharField(blank=True, help_text='Ein-Satz-Intro für Session-Cards', max_length=300, verbose_name='Kurz-Intro')),
                ('is_keynote', models.BooleanField(default=False, verbose_name='Keynote-Speaker')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='lma_people.personprofile')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'ordering': ['-is_keynote', 'profile__user__last_name'],
            },
        ),
    ]
