# Generated by Django 6.0.5 on 2026-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='category',
            field=models.CharField(choices=[('delegate', 'Delegate'), ('speaker', 'Speaker'), ('organizer', 'Organizer'), ('committee', 'Committee / Reviewer'), ('company', 'Company / Industry'), ('staff', 'Staff'), ('press', 'Press'), ('student', 'Student'), ('other', 'Other')], default='delegate', help_text='Type of participant — drives badge layout, list filters and access rules', max_length=20, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='social_event_registered',
            field=models.BooleanField(default=False, help_text='Tick when the participant has booked/paid the social evening', verbose_name='Registered for social event'),
        ),
    ]
