# Generated by Django 6.0.5 on 2026-05-09 08:15

from django.db import migrations, models

import lma_connect.plugins.access.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=lma_connect.plugins.access.models._gen_token, help_text='Wird im QR-Code kodiert', max_length=32, unique=True, verbose_name='Token')),
                ('label', models.CharField(blank=True, help_text="Für Orga, z. B. 'Speaker-Slot 12' oder 'Reserve'", max_length=200, verbose_name='Label (intern)')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivieren = Token kann nicht mehr eingelöst werden', verbose_name='Aktiv')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingelöst am')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesehen')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen (intern)')),
            ],
            options={
                'verbose_name': 'Access-Token',
                'verbose_name_plural': 'Access-Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
