# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_access', '0001_initial'),
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='lma_core.event'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Erstellt beim ersten Einlösen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
