# Generated by Django 6.0.5 on 2026-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_access', '0003_ops_not_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='category',
            field=models.CharField(choices=[('delegate', 'Delegate'), ('speaker', 'Speaker'), ('organizer', 'Organizer'), ('committee', 'Committee / Reviewer'), ('company', 'Company / Industry'), ('staff', 'Staff'), ('press', 'Press'), ('student', 'Student'), ('other', 'Other')], default='delegate', help_text="Participant group this QR batch belongs to (Delegate, Speaker, Industry …) — assigned to the attendee's profile on first redemption", max_length=20, verbose_name='Group / Category'),
        ),
    ]
