# Generated by Django 6.0.5 on 2026-08-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0010_accessattemptexpiration'),
        ('lma_access', '0004_accesstoken_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
            ],
            options={
                'verbose_name': 'Failed login attempt',
                'verbose_name_plural': 'Failed login attempts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('axes.accessattempt',),
        ),
        migrations.CreateModel(
            name='LoginFailureLog',
            fields=[
            ],
            options={
                'verbose_name': 'Login failure log',
                'verbose_name_plural': 'Login failure log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('axes.accessfailurelog',),
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
            ],
            options={
                'verbose_name': 'Login log',
                'verbose_name_plural': 'Login log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('axes.accesslog',),
        ),
    ]
