# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_core', '0001_initial'),
        ('lma_people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=400, verbose_name='Frage')),
                ('type', models.CharField(choices=[('single', 'Single choice'), ('multi', 'Multi choice'), ('open', 'Open text')], default='single', max_length=20, verbose_name='Typ')),
                ('opens_at', models.DateTimeField(blank=True, help_text='Leer = manuelle Aktivierung', null=True, verbose_name='Öffnet')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Schließt')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('is_results_public', models.BooleanField(default=True, verbose_name='Ergebnisse für Teilnehmer sichtbar')),
            ],
            options={
                'verbose_name': 'Live-Umfrage',
                'verbose_name_plural': 'Live-Umfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivePollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Antwort')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lma_program.livepoll')),
            ],
            options={
                'ordering': ['poll', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('summary', models.TextField(blank=True, verbose_name='Zusammenfassung (Markdown)')),
                ('type', models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Oral communication'), ('panel', 'Panel discussion'), ('workshop', 'Workshop'), ('symposium', 'Symposium'), ('break', 'Break / Catering'), ('poster', 'Poster session')], default='talk', max_length=20, verbose_name='Typ')),
                ('starts_at', models.DateTimeField(verbose_name='Beginn')),
                ('ends_at', models.DateTimeField(verbose_name='Ende')),
                ('qa_enabled', models.BooleanField(default=True, help_text='Teilnehmer dürfen während der Session Fragen einreichen', verbose_name='Live-Q&A aktiv')),
                ('qa_moderated', models.BooleanField(default=True, help_text='Fragen werden vor Anzeige freigegeben', verbose_name='Q&A moderiert')),
                ('rating_enabled', models.BooleanField(default=True, verbose_name='Bewertung zugelassen')),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lma_core.event')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='lma_core.room')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['starts_at', 'track'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asker_display_name', models.CharField(blank=True, help_text='Pseudonym — leer bei Klarnamen-Posting', max_length=80, verbose_name='Anzeigename')),
                ('text', models.TextField(max_length=2000, verbose_name='Frage')),
                ('is_approved', models.BooleanField(default=False, help_text='Bei moderierten Sessions Pflicht; sonst auto-True', verbose_name='Freigegeben')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Beantwortet')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Beantwortet am')),
                ('flagged_count', models.PositiveSmallIntegerField(default=0, verbose_name='Gemeldet')),
                ('asker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lma_program.session')),
            ],
            options={
                'verbose_name': 'Live-Q&A-Frage',
                'verbose_name_plural': 'Live-Q&A-Fragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='livepoll',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='lma_program.session'),
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_slides', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Slides')),
                ('rating_clarity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Verständlichkeit (Englisch)')),
                ('rating_relevance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Practical relevance')),
                ('rating_overall', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar (Markdown, optional)')),
                ('is_anonymous', models.BooleanField(default=True, help_text='Schützt rohe Auswertung; Aggregation bleibt sichtbar', verbose_name='Anonym anzeigen')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='lma_program.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session-Bewertung',
                'verbose_name_plural': 'Session-Bewertungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('speaker', 'Speaker'), ('co_author', 'Co-author'), ('discussant', 'Discussant')], default='speaker', max_length=20, verbose_name='Rolle')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='lma_program.session')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignments', to='lma_people.speaker')),
            ],
            options={
                'verbose_name': 'Session-Speaker',
                'verbose_name_plural': 'Session-Speakers',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('color', models.CharField(default='#206bc4', help_text='Hex inkl. # — Akzent auf Session-Cards', max_length=7, verbose_name='Farbe')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['event', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='lma_program.track'),
        ),
        migrations.CreateModel(
            name='LivePollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True, verbose_name='Freitext-Antwort')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lma_program.livepolloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lma_program.livepoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live-Umfrage-Antwort',
                'verbose_name_plural': 'Live-Umfrage-Antworten',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('poll', 'user', 'option'), name='uniq_poll_user_option')],
            },
        ),
        migrations.CreateModel(
            name='QuestionUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='lma_program.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['session', 'is_approved'], name='lma_program_session_5312fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionrating',
            unique_together={('session', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionspeaker',
            unique_together={('session', 'speaker', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('event', 'slug')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['event', 'starts_at'], name='lma_program_event_i_a1997f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['track', 'starts_at'], name='lma_program_track_i_34ff30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('event', 'slug')},
        ),
    ]
