# Generated by Django 6.0.5 on 2026-05-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_by_chair',
            field=models.ForeignKey(blank=True, help_text='Set when the chair prepared this question themselves', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Chair marked this to actually be asked', verbose_name='Starred by chair'),
        ),
        migrations.AddField(
            model_name='question',
            name='starred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starred at'),
        ),
        migrations.CreateModel(
            name='SessionChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='lma_program.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaired_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session chair',
                'verbose_name_plural': 'Session chairs',
                'ordering': ['session', 'order'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
