# Generated by Django 6.0.5 on 2026-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_program', '0002_question_added_by_chair_question_is_starred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='qa_moderated',
            field=models.BooleanField(default=False, help_text='Off (default): questions appear immediately, everyone can up-vote, and the chair stars the ones to be asked. On: questions stay hidden until the chair approves them — use for sensitive sessions.', verbose_name='Q&A pre-moderated'),
        ),
    ]
