# Generated by Django 6.0.5 on 2026-07-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_program', '0004_alter_livepoll_is_results_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='screen_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lma_program.livepoll', verbose_name='Projizierte Umfrage'),
        ),
        migrations.AddField(
            model_name='session',
            name='screen_source',
            field=models.CharField(choices=[('standby', 'Standby'), ('qa', 'Q&A'), ('poll', 'Umfrage-Ergebnisse')], default='standby', max_length=10, verbose_name='Beamer-Quelle'),
        ),
    ]
