# Generated by Django 6.0.5 on 2026-05-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Must match a rule in services.ACHIEVEMENT_RULES', unique=True, verbose_name='Key')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('icon_class', models.CharField(default='ti-award', help_text="e.g. 'ti-trophy', 'ti-message-circle'", max_length=60, verbose_name='Tabler icon class')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('question_asked', 'Asked a question'), ('question_upvoted', 'Up-voted a question'), ('poll_voted', 'Voted in a live poll'), ('session_rated', 'Rated a session'), ('survey_submitted', 'Submitted the feedback survey')], max_length=30, verbose_name='Action')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Points')),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Dedup key')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='lma_core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score entry',
                'verbose_name_plural': 'Score entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event'], name='lma_gamific_user_id_d9ee2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Awarded at')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='lma_gamification.achievement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='lma_core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User achievement',
                'verbose_name_plural': 'User achievements',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'event', 'achievement')},
            },
        ),
    ]
