# Generated by Django 6.0.5 on 2026-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_gamification', '0004_seed_expo_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='action',
            field=models.CharField(choices=[('question_asked', 'Asked a question'), ('question_upvoted', 'Up-voted a question'), ('poll_voted', 'Voted in a live poll'), ('session_rated', 'Rated a session'), ('survey_submitted', 'Submitted the feedback survey'), ('booth_checkin', 'Checked in at an exhibitor booth'), ('booth_quiz', 'Answered a booth quiz correctly'), ('poster_checkin', 'Checked in at a poster'), ('poster_rated', 'Rated a poster'), ('abstract_starred', 'Gave a star to an abstract')], max_length=30, verbose_name='Action'),
        ),
    ]
