# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="z. B. 'Feedback Summit 2026'", max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('intro_text', models.TextField(blank=True, verbose_name='Einleitungstext (Markdown)')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='Öffnet')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Schließt')),
                ('is_published', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('allow_anonymous', models.BooleanField(default=True, help_text='Wenn aus: Login erforderlich, Antworten dem User zugeordnet', verbose_name='Anonyme Teilnahme erlauben')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Event-Umfrage',
                'verbose_name_plural': 'Event-Umfragen',
                'ordering': ['event', '-created_at'],
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400, verbose_name='Frage')),
                ('help_text', models.CharField(blank=True, help_text="Optional — z. B. Likert-Endpunkte '1=zu kurz, 5=zu lang'", max_length=300, verbose_name='Hilfetext')),
                ('type', models.CharField(choices=[('yes_no', 'Yes / No'), ('likert_5', 'Likert scale 1–5'), ('open_text', 'Open text'), ('multi_choice', 'Multiple choice'), ('single_choice', 'Single choice')], max_length=20, verbose_name='Typ')),
                ('is_required', models.BooleanField(default=False, verbose_name='Pflichtfeld')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('likert_min_label', models.CharField(blank=True, help_text="z. B. 'zu kurz'", max_length=40, verbose_name='Likert min Label')),
                ('likert_max_label', models.CharField(blank=True, help_text="z. B. 'zu lang'", max_length=40, verbose_name='Likert max Label')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lma_feedback.eventsurvey')),
            ],
            options={
                'verbose_name': 'Umfrage-Frage',
                'verbose_name_plural': 'Umfrage-Fragen',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('value', models.CharField(blank=True, help_text='Optional — interner Wert (sonst = text)', max_length=80, verbose_name='Wert')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lma_feedback.surveyquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgesendet am')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lma_feedback.eventsurvey')),
                ('user', models.ForeignKey(blank=True, help_text='NULL = anonym (sofern allow_anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Umfrage-Antwort',
                'verbose_name_plural': 'Umfrage-Antworten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Ja/Nein-Wert')),
                ('value_int', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Likert-Wert')),
                ('value_text', models.TextField(blank=True, verbose_name='Freitext-Wert')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='lma_feedback.surveychoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lma_feedback.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lma_feedback.surveyresponse')),
            ],
            options={
                'ordering': ['response', 'question__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('survey', 'user'), name='uniq_survey_user_response'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question', 'choice'), name='uniq_response_question_choice'),
        ),
    ]
