# Generated by Django 6.0.5 on 2026-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_feedback', '0002_english_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsurvey',
            name='intro_text_de',
            field=models.TextField(blank=True, verbose_name='Introduction — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='eventsurvey',
            name='title_de',
            field=models.CharField(blank=True, help_text='Leave empty and the English text is shown to German-speaking visitors too', max_length=200, verbose_name='Title (DE)'),
        ),
        migrations.AddField(
            model_name='surveychoice',
            name='text_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Text (DE)'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='help_text_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='Help text (DE)'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='likert_max_label_de',
            field=models.CharField(blank=True, max_length=40, verbose_name='Likert label (max, DE)'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='likert_min_label_de',
            field=models.CharField(blank=True, max_length=40, verbose_name='Likert label (min, DE)'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='text_de',
            field=models.CharField(blank=True, max_length=400, verbose_name='Question (DE)'),
        ),
    ]
