# Generated by Django 6.0.5 on 2026-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('poster', 'Poster'), ('oral', 'Oral communication'), ('keynote', 'Keynote')], default='poster', max_length=20, verbose_name='Typ')),
                ('poster_id', models.CharField(blank=True, help_text='z. B. P-042 für Poster Nr. 42, O-15 für Oral 15', max_length=20, verbose_name='Poster-/Talk-ID')),
                ('location', models.CharField(blank=True, help_text='Wo das Poster hängt — z. B. Foyer A, Wand 5', max_length=200, verbose_name='Lokation')),
                ('title', models.CharField(max_length=400, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=240, verbose_name='Slug')),
                ('abstract_text', models.TextField(help_text='Hauptinhalt — typisch 250–300 Wörter', verbose_name='Abstract-Text (Markdown)')),
                ('keywords', models.CharField(blank=True, help_text='Komma-separiert', max_length=400, verbose_name='Keywords')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20, verbose_name='Status')),
                ('decision_notes', models.TextField(blank=True, verbose_name='Entscheidungsnotizen (intern)')),
                ('award', models.CharField(blank=True, choices=[('best_poster', 'Best Poster'), ('best_oral', 'Best Oral Presentation'), ('audience_choice', 'Audience Choice Award'), ('innovation', 'Innovation Award'), ('young_investigator', 'Young Investigator Award'), ('jury_special', 'Jury Special Mention')], help_text='Wenn gesetzt, wird der Abstract als Preisträger markiert', max_length=30, verbose_name='Auszeichnung')),
                ('award_note', models.CharField(blank=True, help_text="Kurzer Text, z. B. 'Highest impact factor in study design'", max_length=300, verbose_name='Award-Begründung (optional)')),
                ('award_at', models.DateField(blank=True, null=True, verbose_name='Auszeichnungs-Datum')),
                ('is_published', models.BooleanField(default=False, verbose_name='Öffentlich sichtbar')),
            ],
            options={
                'verbose_name': 'Abstract',
                'verbose_name_plural': 'Abstracts',
                'ordering': ['event', 'type', 'poster_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AbstractAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Auch ohne User-Account → Klartext', max_length=200, verbose_name='Vollständiger Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='Affiliation')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('is_presenting', models.BooleanField(default=False, verbose_name='Vortragender / Präsentierende:r')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Korrespondenz-Autor')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Abstract-Autor',
                'verbose_name_plural': 'Abstract-Autor:innen',
                'ordering': ['abstract', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AbstractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('color', models.CharField(default='#206bc4', max_length=7, verbose_name='Farbe')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Abstract-Kategorie',
                'verbose_name_plural': 'Abstract-Kategorien',
                'ordering': ['event', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AbstractReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Nummer')),
                ('citation_text', models.TextField(help_text='Volltext-Zitation, z. B. Smith J et al. Nature 2024;612:45-53', verbose_name='Zitation')),
                ('doi', models.CharField(blank=True, max_length=120, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['abstract', 'order'],
            },
        ),
    ]
