# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_abstracts', '0001_initial'),
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='lma_core.event'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_abstracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractauthor',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='lma_abstracts.abstract'),
        ),
        migrations.AddField(
            model_name='abstractauthor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional — wenn der Autor einen Account hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstract_authorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abstractcategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_categories', to='lma_core.event'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstracts', to='lma_abstracts.abstractcategory'),
        ),
        migrations.AddField(
            model_name='abstractreference',
            name='abstract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='lma_abstracts.abstract'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractcategory',
            unique_together={('event', 'slug')},
        ),
        migrations.AddIndex(
            model_name='abstract',
            index=models.Index(fields=['event', 'status'], name='lma_abstrac_event_i_2ea849_idx'),
        ),
        migrations.AddIndex(
            model_name='abstract',
            index=models.Index(fields=['event', 'category'], name='lma_abstrac_event_i_370ab5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='abstract',
            unique_together={('event', 'slug')},
        ),
    ]
