# Generated by Django 6.0.5 on 2026-06-16 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_abstracts', '0002_initial'),
        ('lma_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Farbe')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_tags', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Abstract-Tag',
                'verbose_name_plural': 'Abstract-Tags',
                'ordering': ['event', 'name'],
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='abstract',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='abstracts', to='lma_abstracts.abstracttag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AbstractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — exzellent'), (2, '2 — sehr gut'), (3, '3 — gut'), (4, '4 — grenzwertig'), (5, '5 — schwach'), (6, '6 — nicht passend')], null=True, verbose_name='Bewertung 1–6')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar (optional)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Wird beim ersten Score-Submit gesetzt', null=True, verbose_name='Abgegeben am')),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lma_abstracts.abstract')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abstract-Review',
                'verbose_name_plural': 'Abstract-Reviews',
                'ordering': ['abstract', 'reviewer'],
                'indexes': [models.Index(fields=['reviewer', 'score'], name='lma_abstrac_reviewe_b58bee_idx')],
                'unique_together': {('abstract', 'reviewer')},
            },
        ),
    ]
