# Generated by Django 6.0.5 on 2026-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_abstracts', '0003_abstracttag_abstract_tags_abstractreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='peer_review',
            field=models.TextField(blank=True, help_text='AI-generated pre-review for committee members — shown on the review page as a helper / second opinion. Markdown supported.', verbose_name='PEER pre-review (Markdown)'),
        ),
    ]
