# Generated by Django 6.0.5 on 2026-08-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_abstracts', '0005_reviewers_not_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='has_poster',
            field=models.BooleanField(default=False, help_text='Für dieses Abstract hängt ein Poster mit QR-Code — auch bei Vorträgen möglich, die zusätzlich ein Poster zeigen', verbose_name='Poster hängt aus'),
        ),
        migrations.CreateModel(
            name='AbstractStarVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_votes', to='lma_abstracts.abstract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_star_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publikums-Stern',
                'verbose_name_plural': 'Publikums-Sterne',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'abstract'], name='lma_abstrac_user_id_d0e131_idx')],
                'unique_together': {('abstract', 'user')},
            },
        ),
    ]
