# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, help_text='Upload nur durch Orga (kein Self-Service — XXE/XSS-Schutz)', null=True, upload_to='sponsors/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='sponsors/banners/', verbose_name='Banner')),
                ('bio_short', models.CharField(blank=True, help_text='Ein-Satz-Pitch für die Sponsor-Übersicht', max_length=300, verbose_name='Kurz-Bio')),
                ('bio_long', models.TextField(blank=True, verbose_name='Vollständige Bio (Markdown)')),
                ('website', models.URLField(blank=True, verbose_name='Webseite')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Kontakt-E-Mail')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Ansprechperson')),
                ('booth_location', models.CharField(blank=True, help_text="z. B. 'Foyer A — Stand B12'", max_length=200, verbose_name='Stand-Lokation')),
                ('booth_x', models.DecimalField(blank=True, decimal_places=4, help_text='0.0 = links, 1.0 = rechts', max_digits=5, null=True, verbose_name='Floorplan X')),
                ('booth_y', models.DecimalField(blank=True, decimal_places=4, help_text='0.0 = oben, 1.0 = unten', max_digits=5, null=True, verbose_name='Floorplan Y')),
                ('highlights_md', models.TextField(blank=True, help_text='Stichpunkte zu Produkten/Neuheiten — wird auf der Detailseite hervorgehoben', verbose_name='Highlights (Markdown)')),
                ('contract_signed_at', models.DateField(blank=True, null=True, verbose_name='Vertrag unterzeichnet')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Bezahlt')),
                ('notes_internal', models.TextField(blank=True, help_text='Nicht öffentlich sichtbar', verbose_name='Interne Notizen')),
                ('is_published', models.BooleanField(default=False, verbose_name='Öffentlich anzeigen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge innerhalb Tier')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsoren',
                'ordering': ['event', 'tier__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role', models.CharField(blank=True, help_text="z. B. 'Sales Manager DACH'", max_length=200, verbose_name='Rolle')),
                ('expertise', models.CharField(blank=True, help_text="z. B. 'Hämatologie, POC-Diagnostik'", max_length=300, verbose_name='Field of expertise')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sponsors/contacts/', verbose_name='Foto')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='lma_sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'Ansprechperson',
                'verbose_name_plural': 'Ansprechpersonen',
                'ordering': ['sponsor', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Short description')),
                ('file', models.FileField(upload_to='sponsors/downloads/', verbose_name='File')),
                ('type', models.CharField(choices=[('whitepaper', 'Whitepaper / Study'), ('datasheet', 'Datasheet'), ('brochure', 'Brochure'), ('presentation', 'Presentation / Slides'), ('manual', 'Manual / User guide'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='lma_sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor download',
                'verbose_name_plural': 'Sponsor downloads',
                'ordering': ['sponsor', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='sponsors/images/', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lma_sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor-Bild',
                'verbose_name_plural': 'Sponsor-Bilder',
                'ordering': ['sponsor', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Label')),
                ('url', models.URLField(verbose_name='URL')),
                ('type', models.CharField(choices=[('product', 'Product'), ('news', 'News'), ('whitepaper', 'Whitepaper / Study'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20, verbose_name='Typ')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lma_sponsors.sponsor')),
            ],
            options={
                'ordering': ['sponsor', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('color', models.CharField(default='#f59e0b', help_text='Hex inkl. # — z. B. Gold = #f59e0b', max_length=7, verbose_name='Farbe')),
                ('perks_md', models.TextField(blank=True, help_text='Aufzählung was im Paket enthalten ist', verbose_name='Leistungen (Markdown)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis (EUR)')),
                ('slot_count', models.PositiveSmallIntegerField(default=0, help_text='0 = unbegrenzt', verbose_name='Anzahl Slots')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 = top', verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_tiers', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Sponsor-Stufe',
                'verbose_name_plural': 'Sponsor-Stufen',
                'ordering': ['event', 'order', 'name'],
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='lma_sponsors.sponsortier'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together={('event', 'slug')},
        ),
    ]
