# Generated by Django 6.0.5 on 2026-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='bio_long_en',
            field=models.TextField(blank=True, verbose_name='Vollständige Bio — EN (Markdown)'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='bio_short_en',
            field=models.CharField(blank=True, help_text='Leer lassen = deutscher Text wird auch englisch gezeigt', max_length=300, verbose_name='Kurz-Bio (EN)'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='booth_location_en',
            field=models.CharField(blank=True, help_text="z. B. 'Foyer A — Booth B12'", max_length=200, verbose_name='Stand-Lokation (EN)'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='highlights_md_en',
            field=models.TextField(blank=True, verbose_name='Highlights — EN (Markdown)'),
        ),
        migrations.AddField(
            model_name='sponsorcontact',
            name='expertise_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Field of expertise (EN)'),
        ),
        migrations.AddField(
            model_name='sponsorcontact',
            name='role_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rolle (EN)'),
        ),
        migrations.AddField(
            model_name='sponsordownload',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Short description (EN)'),
        ),
        migrations.AddField(
            model_name='sponsordownload',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='sponsorimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift (EN)'),
        ),
        migrations.AddField(
            model_name='sponsorlink',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung (EN)'),
        ),
        migrations.AddField(
            model_name='sponsorlink',
            name='label_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Label (EN)'),
        ),
    ]
