# Generated by Django 6.0.5 on 2026-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_sponsors', '0002_sponsor_bio_long_en_sponsor_bio_short_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Logo erscheint auf dem Welcome-Screen und im Kopfbereich der Startseite. Nur wirksam, wenn auch „Öffentlich anzeigen“ gesetzt und ein Logo hinterlegt ist.', verbose_name='Hauptsponsor (Startseite)'),
        ),
    ]
