# Generated by Django 6.0.5 on 2026-05-09 08:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(blank=True, help_text="e.g. 'Department of Laboratory Medicine'", max_length=200, verbose_name='Department')),
                ('institution', models.CharField(blank=True, help_text="e.g. 'University Hospital Salzburg'", max_length=200, verbose_name='Institution')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Country')),
                ('country_iso', models.CharField(blank=True, help_text="e.g. 'AT' — for flag display", max_length=2, verbose_name='ISO-3166')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Untertitel')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('timezone_name', models.CharField(default='Europe/Vienna', max_length=64, verbose_name='Zeitzone')),
                ('venue_name', models.CharField(blank=True, max_length=200, verbose_name='Veranstaltungsort')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Stadt')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Land')),
                ('country_iso', models.CharField(blank=True, max_length=2, verbose_name='ISO-3166')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (Markdown)')),
                ('homepage_url', models.URLField(blank=True, verbose_name='Homepage')),
                ('theme_color', models.CharField(default='#206bc4', help_text='Hex inkl. # — z. B. #206bc4', max_length=7, verbose_name='Theme-Farbe')),
                ('accent_color', models.CharField(default='#79a6dc', max_length=7, verbose_name='Akzent-Farbe')),
                ('logo', models.ImageField(blank=True, help_text='Wird oben in der Topbar angezeigt', null=True, upload_to='events/event_logos/', verbose_name='Event-Logo (Header)')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner')),
                ('welcome_image', models.ImageField(blank=True, help_text='Hauptbild auf der Startseite (Welcome-Screen)', null=True, upload_to='events/welcome/', verbose_name='Welcome-Hero-Bild')),
                ('organizer_name', models.CharField(blank=True, help_text="e.g. 'LabMedAlliance' — shown in the footer", max_length=200, verbose_name='Organizer name')),
                ('organizer_logo', models.ImageField(blank=True, help_text='Shown in the footer and on the welcome screen', null=True, upload_to='events/organizer_logos/', verbose_name='Organizer logo (footer)')),
                ('organizer_url', models.URLField(blank=True, verbose_name='Organizer URL')),
                ('footer_label', models.CharField(default='Hosted by', help_text='Customisable label preceding the organizer logo', max_length=80, verbose_name="Footer 'hosted by' label")),
                ('copyright_holder', models.CharField(blank=True, help_text='Defaults to organizer name if empty', max_length=200, verbose_name='Copyright holder')),
                ('copyright_year_start', models.PositiveSmallIntegerField(blank=True, help_text='Year the copyright begins; defaults to event year if empty', null=True, verbose_name='Copyright start year')),
                ('imprint_md', models.TextField(blank=True, help_text='Required in DACH (ECG §5 AT / TMG §5 DE). Served at /legal/imprint/.', verbose_name='Imprint (Markdown)')),
                ('privacy_md', models.TextField(blank=True, help_text='Required by DSGVO Art. 13. Cover: data collected, purpose, retention, rights, hosting, contact.', verbose_name='Privacy policy (Markdown)')),
                ('terms_md', models.TextField(blank=True, help_text='Optional — terms & conditions of attendance.', verbose_name='Terms of use (Markdown)')),
                ('accessibility_md', models.TextField(blank=True, help_text='Optional but recommended for public bodies.', verbose_name='Accessibility statement (Markdown)')),
                ('footer_extra_md', models.TextField(blank=True, help_text='Free-form line displayed below the legal links', verbose_name='Extra footer text (Markdown)')),
                ('floorplan', models.FileField(blank=True, help_text='PDF, PNG oder SVG. Wird auf der Detail-Seite angezeigt.', null=True, upload_to='events/floorplans/', verbose_name='Floorplan')),
                ('travel_info', models.TextField(blank=True, help_text='Zug, Flughafen, ÖPNV, Parkplätze', verbose_name='Anreise-Infos (Markdown)')),
                ('sightseeing_info', models.TextField(blank=True, help_text='Empfehlungen für Aufenthalt vor Ort', verbose_name='Sightseeing (Markdown)')),
                ('general_info', models.TextField(blank=True, help_text='WLAN, Catering, Notfallnummern, Hashtag, Dresscode etc.', verbose_name='Sonstige Infos (Markdown)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Public')),
                ('tab_program_enabled', models.BooleanField(default=True, verbose_name='Show Program tab')),
                ('tab_sponsors_enabled', models.BooleanField(default=True, verbose_name='Show Sponsors tab')),
                ('tab_abstracts_enabled', models.BooleanField(default=True, verbose_name='Show Abstracts tab')),
                ('tab_info_enabled', models.BooleanField(default=True, verbose_name='Show Info tab')),
                ('tab_feedback_enabled', models.BooleanField(default=True, verbose_name='Show Feedback tab')),
                ('organizing_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_secretary', to=settings.AUTH_USER_MODEL, verbose_name='Organizing Secretary')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('organizing', 'Organizing committee'), ('scientific', 'Scientific committee'), ('local', 'Local committee'), ('advisory', 'Advisory board')], max_length=20, verbose_name='Typ')),
                ('name', models.CharField(help_text="Frei benennbar — z. B. 'Scientific Committee 2026'", max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Komitee',
                'verbose_name_plural': 'Komitees',
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'type')},
            },
        ),
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('secretary', 'Organizing Secretary'), ('registration', 'Registration'), ('sponsoring', 'Sponsoring'), ('abstracts', 'Abstracts / Scientific'), ('press', 'Press'), ('technical', 'Technical / IT'), ('other', 'Other')], default='secretary', max_length=20, verbose_name='Role')),
                ('name', models.CharField(help_text='Person or organization name displayed first', max_length=200, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company / Organization')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (Markdown)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Event contact',
                'verbose_name_plural': 'Event contacts',
                'ordering': ['event', 'order', 'role'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('co_chair', 'Co-Chair'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=20, verbose_name='Rolle')),
                ('affiliation', models.CharField(blank=True, help_text='Überschreibt Profil-Affiliation falls gesetzt', max_length=200, verbose_name='Affiliation')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='lma_core.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komitee-Mitgliedschaft',
                'verbose_name_plural': 'Komitee-Mitgliedschaften',
                'ordering': ['committee', 'order', 'user__last_name'],
                'unique_together': {('committee', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('newsletter', 'Newsletter'), ('profile_public', 'Profil öffentlich anzeigen'), ('photo_usage', 'Foto-/Video-Nutzung'), ('qa_real_name', 'Q&A-Beiträge unter Klarnamen statt Pseudonym')], max_length=30, verbose_name='Typ')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='Erteilt am')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Widerrufen am')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Einwilligung',
                'verbose_name_plural': 'Einwilligungen',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapazität')),
                ('floor', models.CharField(blank=True, max_length=40, verbose_name='Stockwerk')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ['event', 'order', 'name'],
                'unique_together': {('event', 'slug')},
            },
        ),
    ]
