# Generated by Django 6.0.5 on 2026-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility_md_de',
            field=models.TextField(blank=True, verbose_name='Accessibility — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresse (DE)'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Beschreibung — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='footer_extra_md_de',
            field=models.TextField(blank=True, verbose_name='Extra footer text — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='general_info_de',
            field=models.TextField(blank=True, verbose_name='Sonstige Infos — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='imprint_md_de',
            field=models.TextField(blank=True, verbose_name='Imprint — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='privacy_md_de',
            field=models.TextField(blank=True, verbose_name='Privacy policy — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='sightseeing_info_de',
            field=models.TextField(blank=True, verbose_name='Sightseeing — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle_de',
            field=models.CharField(blank=True, max_length=300, verbose_name='Untertitel (DE)'),
        ),
        migrations.AddField(
            model_name='event',
            name='terms_md_de',
            field=models.TextField(blank=True, verbose_name='Terms of use — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='travel_info_de',
            field=models.TextField(blank=True, verbose_name='Anreise-Infos — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veranstaltungsort (DE)'),
        ),
    ]
