# Generated by Django 6.0.5 on 2026-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0002_event_accessibility_md_de_event_address_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_event_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Social-Event address'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Social-Event city'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Social-Event end'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_info',
            field=models.TextField(blank=True, help_text='Dresscode, Catering, Programm, Kosten etc.', verbose_name='Social-Event details (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_info_de',
            field=models.TextField(blank=True, verbose_name='Social-Event details — DE (Markdown)'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_meeting_point',
            field=models.CharField(blank=True, help_text="z. B. 'Foyer Hauptgebäude'", max_length=200, verbose_name='Meeting point'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_meeting_time',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt am Treffpunkt (für gemeinsamen Transfer)', null=True, verbose_name='Meeting time'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Social-Event start'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_title',
            field=models.CharField(blank=True, help_text="z. B. 'Data & Drinks Networking'", max_length=200, verbose_name='Social-Event title'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_event_venue_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Social-Event venue'),
        ),
    ]
