# Generated by Django 6.0.5 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0003_event_social_event_address_event_social_event_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_event_url',
            field=models.URLField(blank=True, help_text='Optional — Restaurant/Bar/Location URL', verbose_name='Social-Event venue website'),
        ),
    ]
