# Generated by Django 6.0.5 on 2026-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0004_event_social_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, help_text='Kompakter Name für Topbar & Homescreen-Icon (z. B. „ACME 2026“). Fallback: Name.', max_length=40, verbose_name='Kurzname'),
        ),
    ]
