# Generated by Django 6.0.5 on 2026-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0005_event_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='floorplan_upper',
            field=models.FileField(blank=True, help_text='Optional. Zweiter Plan (1. Stock), wird unter dem Erdgeschoss angezeigt.', null=True, upload_to='events/floorplans/', verbose_name='Floorplan — upper floor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='floorplan',
            field=models.FileField(blank=True, help_text='PDF, PNG oder SVG. Erdgeschoss — Bezugsfläche für die Booth-Pins.', null=True, upload_to='events/floorplans/', verbose_name='Floorplan — ground floor'),
        ),
    ]
