# Generated by Django 6.0.5 on 2026-08-08 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import lma_connect.plugins.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('lma_core', '0006_event_floorplan_upper_alter_event_floorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='general_info',
            field=models.TextField(blank=True, help_text='WiFi, catering, emergency numbers, hashtag, dress code etc. For separate, individually titled sections use the info blocks below.', verbose_name='Sonstige Infos (Markdown)'),
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('icon', models.CharField(blank=True, default='info-circle', help_text="Tabler icon name without the 'ti-' prefix — e.g. 'wifi', 'tools-kitchen-2', 'urgent'. See tabler.io/icons", max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', "Only lowercase letters, digits and hyphens — e.g. 'wifi', 'tools-kitchen-2'.")], verbose_name='Icon')),
                ('body', models.TextField(blank=True, verbose_name='Text (Markdown)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide the block without deleting it.', verbose_name='Published')),
                ('title_de', models.CharField(blank=True, max_length=200, verbose_name='Titel (DE)')),
                ('body_de', models.TextField(blank=True, verbose_name='Text — DE (Markdown)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='lma_core.event')),
            ],
            options={
                'verbose_name': 'Info block',
                'verbose_name_plural': 'Info blocks',
                'ordering': ['event', 'order', 'id'],
            },
            bases=(lma_connect.plugins.core.models.TranslatedTextMixin, models.Model),
        ),
    ]
