# Generated by Django 6.0.5 on 2026-07-05 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lma_abstracts', '0005_reviewers_not_staff'),
        ('lma_sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='Antwort sollte am Stand zu finden / erfragbar sein', max_length=300, verbose_name='Frage')),
                ('hint', models.CharField(blank=True, help_text="z. B. 'Frag das Standpersonal' oder 'siehe Roll-up'", max_length=200, verbose_name='Hinweis (optional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lma_sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'Stand-Quiz',
                'verbose_name_plural': 'Stand-Quizze',
            },
        ),
        migrations.CreateModel(
            name='BoothChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Antworttext')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Richtig')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lma_expo.boothquiz')),
            ],
            options={
                'verbose_name': 'Antwortoption',
                'verbose_name_plural': 'Antwortoptionen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PosterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sterne')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar (optional)')),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_ratings', to='lma_abstracts.abstract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poster-Bewertung',
                'verbose_name_plural': 'Poster-Bewertungen',
                'ordering': ['-created_at'],
                'unique_together': {('abstract', 'user')},
            },
        ),
    ]
